language: node_js
node_js:
  - "8.10.0"

addons:
  chrome: stable
  sonarcloud:
    organization: "dev-saas"

cache:
  directories:
    - node_modules

services:
  - mongodb
  - redis-server

install:
  - npm install

script:
  - npm test

after_success:
  - sonar-scanner

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master